package services

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/jadb/git-hop/internal/config"
	"github.com/jadb/git-hop/internal/docker"
	"github.com/spf13/afero"
)

// EnvManager manages the environment
type EnvManager struct {
	Ports   *PortAllocator
	Volumes *VolumeManager
	Docker  *docker.Docker
	fs      afero.Fs
}

// NewEnvManager creates a new env manager
func NewEnvManager(fs afero.Fs, portsCfg *config.PortsConfig, volsCfg *config.VolumesConfig, d *docker.Docker) *EnvManager {
	return &EnvManager{
		Ports:   NewPortAllocator(portsCfg),
		Volumes: NewVolumeManager(fs, volsCfg),
		Docker:  d,
		fs:      fs,
	}
}

// Generate ensures ports and volumes exist for a branch
func (m *EnvManager) Generate(branch, worktreePath string) (*config.BranchPorts, *config.BranchVolumes, error) {
	serviceNames, err := m.Docker.GetServiceNames(worktreePath)
	if err != nil {
		return nil, nil, err
	}

	existingSvcs := make(map[string]bool)
	for _, s := range m.Ports.Config.Services {
		existingSvcs[s] = true
	}
	for _, s := range serviceNames {
		if !existingSvcs[s] {
			m.Ports.Config.Services = append(m.Ports.Config.Services, s)
		}
	}

	ports, err := m.Ports.AllocatePorts(branch)
	if err != nil {
		return nil, nil, err
	}

	volNames, err := m.Docker.GetVolumeNames(worktreePath)
	if err != nil {
		return nil, nil, err
	}

	vols, err := m.Volumes.CreateVolumes(branch, volNames)
	if err != nil {
		return nil, nil, err
	}

	envPath := filepath.Join(worktreePath, ".env")
	if err := m.writeEnvFile(envPath, ports, vols); err != nil {
		return nil, nil, fmt.Errorf("failed to write .env file: %w", err)
	}

	return &config.BranchPorts{Ports: ports}, &config.BranchVolumes{Volumes: vols}, nil
}

func (m *EnvManager) writeEnvFile(path string, ports map[string]int, vols map[string]string) error {
	var lines []string
	lines = append(lines, "# Generated by git-hop")

	for svc, port := range ports {
		key := fmt.Sprintf("HOP_PORT_%s", strings.ToUpper(svc))
		lines = append(lines, fmt.Sprintf("%s=%d", key, port))
	}

	for vol, path := range vols {
		key := fmt.Sprintf("HOP_VOLUME_%s", strings.ToUpper(vol))
		lines = append(lines, fmt.Sprintf("%s=%s", key, path))
	}

	return afero.WriteFile(m.fs, path, []byte(strings.Join(lines, "\n")), 0644)
}
